-- ALK_RULE_GROUP_DEFINITION definition
CREATE TABLE ALK_RULE_GROUP_DEFINITION
(
    G_ID      NUMBER(10) GENERATED AS IDENTITY PRIMARY KEY,
    G_KEY     VARCHAR2(50)  NOT NULL,
    G_NAME    VARCHAR2(100) NOT NULL,
    G_TYPE    VARCHAR2(20)  NOT NULL,
    G_ENABLED NUMBER(1)     NOT NULL,
    CONSTRAINT UK_ALK_RULE_GROUP_DEFINITION UNIQUE (G_KEY)
);

COMMENT ON TABLE ALK_RULE_GROUP_DEFINITION IS '规则组表';
COMMENT ON COLUMN ALK_RULE_GROUP_DEFINITION.G_ID IS '主键';
COMMENT ON COLUMN ALK_RULE_GROUP_DEFINITION.G_KEY IS '关键字';
COMMENT ON COLUMN ALK_RULE_GROUP_DEFINITION.G_NAME IS '名称';
COMMENT ON COLUMN ALK_RULE_GROUP_DEFINITION.G_TYPE IS '类型';
COMMENT ON COLUMN ALK_RULE_GROUP_DEFINITION.G_ENABLED IS '是否可用';

-- ALK_RULE_DEFINITION definition
CREATE TABLE ALK_RULE_DEFINITION
(
    R_ID       NUMBER(10) GENERATED AS IDENTITY PRIMARY KEY,
    R_TYPE     VARCHAR2(1)    NOT NULL,
    R_NAME     VARCHAR2(100)  NOT NULL,
    R_DESC     VARCHAR2(5000) NOT NULL,
    R_PRIORITY NUMBER(10)     NOT NULL,
    R_SCORE    NUMBER(10)     NOT NULL,
    R_ORDER    NUMBER(10)     NOT NULL,
    R_ENABLED  NUMBER(1)      NOT NULL,
    G_KEY      VARCHAR2(50)   NOT NULL
);

COMMENT ON TABLE ALK_RULE_DEFINITION IS '规则表';
COMMENT ON COLUMN ALK_RULE_DEFINITION.R_ID IS '主键';
COMMENT ON COLUMN ALK_RULE_DEFINITION.R_TYPE IS '类型 1:规则/2:黑名单/3:白名单';
COMMENT ON COLUMN ALK_RULE_DEFINITION.R_NAME IS '名称';
COMMENT ON COLUMN ALK_RULE_DEFINITION.R_DESC IS '描述';
COMMENT ON COLUMN ALK_RULE_DEFINITION.R_PRIORITY IS '优先级';
COMMENT ON COLUMN ALK_RULE_DEFINITION.R_SCORE IS '评分';
COMMENT ON COLUMN ALK_RULE_DEFINITION.R_ORDER IS '顺序';
COMMENT ON COLUMN ALK_RULE_DEFINITION.R_ENABLED IS '是否可用';
COMMENT ON COLUMN ALK_RULE_DEFINITION.G_KEY IS 'ALK_RULE_GROUP_DEFINITION->G_KEY';

-- ALK_RULE_EXT_DEFINITION definition
CREATE TABLE ALK_RULE_EXT_DEFINITION
(
    E_ID    NUMBER(10) GENERATED AS IDENTITY PRIMARY KEY,
    E_KEY   VARCHAR2(100) NOT NULL,
    E_VALUE VARCHAR2(100) NOT NULL,
    R_ID    NUMBER(10)    NOT NULL,
    G_KEY   VARCHAR2(50)  NOT NULL,
    CONSTRAINT UK_ALK_RULE_EXT_DEFINITION UNIQUE (R_ID, E_KEY)
);

COMMENT ON TABLE ALK_RULE_EXT_DEFINITION IS '规则扩展属性表';
COMMENT ON COLUMN ALK_RULE_EXT_DEFINITION.E_ID IS '主键';
COMMENT ON COLUMN ALK_RULE_EXT_DEFINITION.E_KEY IS '属性key';
COMMENT ON COLUMN ALK_RULE_EXT_DEFINITION.E_VALUE IS '属性值';
COMMENT ON COLUMN ALK_RULE_EXT_DEFINITION.R_ID IS 'ALK_RULE_DEFINITION->R_ID';
COMMENT ON COLUMN ALK_RULE_EXT_DEFINITION.G_KEY IS 'ALK_RULE_GROUP_DEFINITION->G_KEY';

-- ALK_RULE_UNIT_DEFINITION definition
CREATE TABLE ALK_RULE_UNIT_DEFINITION
(
    U_ID         NUMBER(10) GENERATED AS IDENTITY PRIMARY KEY,
    U_EXPRESSION VARCHAR2(10000) NOT NULL,
    U_ORDER      NUMBER(10)      NOT NULL,
    U_ENABLED    NUMBER(1)       NOT NULL,
    D_KEY        VARCHAR2(50),
    R_ID         NUMBER(10)      NOT NULL,
    G_KEY        VARCHAR2(50)    NOT NULL
);

COMMENT ON TABLE ALK_RULE_UNIT_DEFINITION IS '规则单元表';
COMMENT ON COLUMN ALK_RULE_UNIT_DEFINITION.U_ID IS '主键';
COMMENT ON COLUMN ALK_RULE_UNIT_DEFINITION.U_EXPRESSION IS '表达式';
COMMENT ON COLUMN ALK_RULE_UNIT_DEFINITION.U_ORDER IS '顺序';
COMMENT ON COLUMN ALK_RULE_UNIT_DEFINITION.U_ENABLED IS '是否可用';
COMMENT ON COLUMN ALK_RULE_UNIT_DEFINITION.D_KEY IS 'ALK_RULE_DATASOURCE_DEFINITION->D_KEY';
COMMENT ON COLUMN ALK_RULE_UNIT_DEFINITION.R_ID IS 'ALK_RULE_DEFINITION->R_ID';
COMMENT ON COLUMN ALK_RULE_UNIT_DEFINITION.G_KEY IS 'ALK_RULE_GROUP_DEFINITION->G_KEY';

-- ALK_RULE_DATASOURCE_DEFINITION definition
CREATE TABLE ALK_RULE_DATASOURCE_DEFINITION
(
    D_ID      NUMBER(10) GENERATED AS IDENTITY PRIMARY KEY,
    D_KEY     VARCHAR2(50)  NOT NULL,
    D_NAME    VARCHAR2(100) NOT NULL,
    D_TYPE    VARCHAR2(20)  NOT NULL,
    D_SCOPE   VARCHAR2(50)  NOT NULL,
    D_ENABLED NUMBER(1)     NOT NULL,
    G_KEY     VARCHAR2(50)  NOT NULL,
    CONSTRAINT UK_ALK_RULE_DATASOURCE_DEFINITION UNIQUE (G_KEY, D_KEY)
);

COMMENT ON TABLE ALK_RULE_DATASOURCE_DEFINITION IS '规则外部数据源表';
COMMENT ON COLUMN ALK_RULE_DATASOURCE_DEFINITION.D_ID IS '主键';
COMMENT ON COLUMN ALK_RULE_DATASOURCE_DEFINITION.D_KEY IS '关键字';
COMMENT ON COLUMN ALK_RULE_DATASOURCE_DEFINITION.D_NAME IS '名称';
COMMENT ON COLUMN ALK_RULE_DATASOURCE_DEFINITION.D_TYPE IS '类型';
COMMENT ON COLUMN ALK_RULE_DATASOURCE_DEFINITION.D_SCOPE IS '数据范围';
COMMENT ON COLUMN ALK_RULE_DATASOURCE_DEFINITION.D_ENABLED IS '是否可用';
COMMENT ON COLUMN ALK_RULE_DATASOURCE_DEFINITION.G_KEY IS 'ALK_RULE_GROUP_DEFINITION->G_KEY';

-- ALK_RULE_DATASOURCE_EXT_DEFINITION definition
CREATE TABLE ALK_RULE_DATASOURCE_EXT_DEFINITION
(
    S_ID    NUMBER(10) GENERATED AS IDENTITY PRIMARY KEY,
    S_KEY   VARCHAR2(100)   NOT NULL,
    S_VALUE VARCHAR2(10000) NOT NULL,
    D_ID    NUMBER(10)      NOT NULL,
    G_KEY   VARCHAR2(50)    NOT NULL,
    CONSTRAINT UK_ALK_RULE_DATASOURCE_EXT_DEFINITION UNIQUE (D_ID, S_KEY)
);

COMMENT ON TABLE ALK_RULE_DATASOURCE_EXT_DEFINITION IS '规则外部数据源扩展属性表';
COMMENT ON COLUMN ALK_RULE_DATASOURCE_EXT_DEFINITION.S_ID IS '主键';
COMMENT ON COLUMN ALK_RULE_DATASOURCE_EXT_DEFINITION.S_KEY IS '属性key';
COMMENT ON COLUMN ALK_RULE_DATASOURCE_EXT_DEFINITION.S_VALUE IS '属性值';
COMMENT ON COLUMN ALK_RULE_DATASOURCE_EXT_DEFINITION.D_ID IS 'ALK_RULE_DATASOURCE_DEFINITION->D_ID';
COMMENT ON COLUMN ALK_RULE_DATASOURCE_EXT_DEFINITION.G_KEY IS 'ALK_RULE_GROUP_DEFINITION->G_KEY';

-- ALK_RULE_PARAM_DEFINITION definition
CREATE TABLE ALK_RULE_PARAM_DEFINITION
(
    P_ID         NUMBER(10) GENERATED AS IDENTITY PRIMARY KEY,
    P_KEY        VARCHAR2(50)    NOT NULL,
    P_NAME       VARCHAR2(100)   NOT NULL,
    P_EXPRESSION VARCHAR2(10000) NOT NULL,
    P_ENABLED    NUMBER(1)       NOT NULL,
    G_KEY        VARCHAR2(50)    NOT NULL,
    CONSTRAINT UK_ALK_RULE_PARAM_DEFINITION UNIQUE (G_KEY, P_KEY)
);

COMMENT ON TABLE ALK_RULE_PARAM_DEFINITION IS '规则入参处理表';
COMMENT ON COLUMN ALK_RULE_PARAM_DEFINITION.P_ID IS '主键';
COMMENT ON COLUMN ALK_RULE_PARAM_DEFINITION.P_KEY IS '关键字';
COMMENT ON COLUMN ALK_RULE_PARAM_DEFINITION.P_NAME IS '名称';
COMMENT ON COLUMN ALK_RULE_PARAM_DEFINITION.P_EXPRESSION IS '表达式';
COMMENT ON COLUMN ALK_RULE_PARAM_DEFINITION.P_ENABLED IS '是否可用';
COMMENT ON COLUMN ALK_RULE_PARAM_DEFINITION.G_KEY IS 'ALK_RULE_GROUP_DEFINITION->G_KEY';

-- ALK_RULE_VARIABLE_DEFINITION definition
CREATE TABLE ALK_RULE_VARIABLE_DEFINITION
(
    V_ID      NUMBER(10) GENERATED AS IDENTITY PRIMARY KEY,
    V_KEY     VARCHAR2(100)  NOT NULL,
    V_NAME    VARCHAR2(100) NOT NULL,
    V_DESC    VARCHAR2(10000),
    V_TYPE    VARCHAR2(10)  NOT NULL,
    V_ORDER   NUMBER(10)    NOT NULL,
    V_ENABLED NUMBER(1)     NOT NULL,
    G_KEY     VARCHAR2(50)  NOT NULL,
    CONSTRAINT UK_ALK_RULE_VARIABLE_DEFINITION UNIQUE (G_KEY, V_KEY)
);

COMMENT ON TABLE ALK_RULE_VARIABLE_DEFINITION IS '规则变量处理表';
COMMENT ON COLUMN ALK_RULE_VARIABLE_DEFINITION.V_ID IS '主键';
COMMENT ON COLUMN ALK_RULE_VARIABLE_DEFINITION.V_KEY IS '关键字';
COMMENT ON COLUMN ALK_RULE_VARIABLE_DEFINITION.V_NAME IS '名称';
COMMENT ON COLUMN ALK_RULE_VARIABLE_DEFINITION.V_DESC IS '描述';
COMMENT ON COLUMN ALK_RULE_VARIABLE_DEFINITION.V_TYPE IS '类型';
COMMENT ON COLUMN ALK_RULE_VARIABLE_DEFINITION.V_ORDER IS '顺序';
COMMENT ON COLUMN ALK_RULE_VARIABLE_DEFINITION.V_ENABLED IS '是否可用';
COMMENT ON COLUMN ALK_RULE_VARIABLE_DEFINITION.G_KEY IS 'ALK_RULE_GROUP_DEFINITION->G_KEY';
